name: Docker Static IP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker net
        run: docker network create --subnet=172.18.0.0/16 mynet

      - name: Run Pyth serv
        run: |
          docker run -d \
            --name my_cont \
            --network mynet \
            --ip 172.18.0.22 \
            -p 2122:2122 \
            ubuntu sleep infinity

          sleep 5

          docker exec my_cont apt-get update
          docker exec my_cont apt-get install -y python3 wget

          docker exec -d my_cont python3 -m http.server 2122

          sleep 5

          docker exec my_cont wget http://172.18.0.22:2122 -O index.html

          docker cp my_cont:/index.html .

      - name: Save artifact
        run: |
          mkdir -p artifacts
          mv index.html artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: homepage
         path: artifacts/index.html


      - name: Clean
        if: always()
        run: |
          docker stop my_cont || true
          docker rm my_cont || true
          docker network rm mynet || true
