name: Docker Static IP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker net
        run: docker network create --subnet=172.18.0.0/16 mynet

      - name: Run Pyth serv
        run: |
          docker run -d \
            --name server_cont \
            --network mynet \
            --ip 172.18.0.22 \
            -p 2122:2122 \
            ubuntu sleep infinity

          sleep 10

          docker exec server_cont apt-get update
          docker exec server_cont apt-get install -y python3 wget

          docker exec server_cont ls -l /

          docker exec -d server_cont python3 -m http.server 2122

          sleep 20

      - name: Dock client
        run: |
          docker run -d \
            --name client_cont \
            --network mynet \
            ubuntu bash -c "apt-get update && apt-get install -y whet && wget -O http://172.18.0.22:2122" >index_dock2.html

            head -c 500 index_dock2.html

      - name: Download from runner
        run: |
          wget http://localhost:2122/ -O index_runner.html

      - name: Save artifact
        run: |
          mkdir -p artifacts

          mv index_dock2.html artifacts/
          mv index_runner.html artifacts/


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: homepage
         path: artifacts/


      - name: Clean
        if: always()
        run: |
          docker stop server_cont || true
          docker rm server_cont || true
          docker network rm mynet || true
